# Generated by Django 5.1.4 on 2025-01-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phonenumber', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Taken_Date', models.DateField()),
                ('Taken_Time', models.TimeField()),
                ('Return_Date', models.DateField()),
                ('Return_Time', models.TimeField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.customers')),
            ],
        ),
    ]
