# Generated by Django 5.1.4 on 2025-01-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Father_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
