# Generated by Django 5.1.4 on 2025-01-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0002_customers_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
