# Generated by Django 5.1.4 on 2025-01-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0003_customeritems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeritems',
            name='Return_Date',
        ),
        migrations.RemoveField(
            model_name='customeritems',
            name='Return_Time',
        ),
    ]
