# Generated by Django 5.1.4 on 2025-01-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0004_remove_customeritems_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerReturnItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountGiven', models.IntegerField()),
                ('Return_Date', models.DateField()),
                ('Return_Time', models.TimeField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.customers')),
                ('CustomerItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.customeritems')),
            ],
        ),
    ]
