# Generated by Django 5.1.4 on 2025-01-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0005_customeritems_amount_customerreturnitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreturnitems',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
