# Generated by Django 5.1.4 on 2025-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0006_customerreturnitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreturnitems',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerreturnitems',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
