# Generated by Django 5.1.4 on 2025-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0007_customerreturnitems_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='Given_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
